<option placeholder="AL">AL - Alderaan</option>
<option placeholder="AP">AP - Amethia Prime</option>
<option placeholder="BE">BE - Bespin</option>
<option placeholder="CA">CA - Corellia</option>
<option placeholder="CO">CO - Coruscant</option>
<option placeholder="DA">DA - Dantooine</option>
<option placeholder="DH">DH - Dagobah</option>
<option placeholder="DU">DU - Duro</option>
<option placeholder="EN">EN - Endor</option>
<option placeholder="FE">FE - Felucia</option>
<option placeholder="HH">HH - Hoth</option>
<option placeholder="HP">HP - Hosnian Prime</option>
<option placeholder="IR">IR - Iridonia</option>
<option placeholder="JK">JK - Jakku</option>
<option placeholder="KL">KL - Kessel</option>
<option placeholder="KO">KO - Korriban</option>
<option placeholder="KY">KY - Kashyyyk</option>
<option placeholder="LM">LM - Lotho Minor</option>
<option placeholder="MA">MA - Mahranee</option>
<option placeholder="MC">MC - Malachor</option>
<option placeholder="MN">MN - Manaan</option>
<option placeholder="MY">MY - Mygeeto</option>
<option placeholder="NA">NA - Naboo</option>
<option placeholder="ON">ON - Onderon</option>
<option placeholder="RY">RY - Ryloth</option>
<option placeholder="SU">SU - Sullust</option>
<option placeholder="TT">TT - Tatooine</option>
<option placeholder="UR">UR - Uranus</option>
<option placeholder="YA">YA - Yavin</option>
